//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Suggestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Suggestions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Puns.Suggestions", typeof(Suggestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fish
        ///furniture
        ///vegetable
        ///cake
        ///baby
        ///machine
        ///time
        ///way
        ///year
        ///work
        ///government
        ///day
        ///man
        ///men
        ///world
        ///life
        ///lives
        ///part
        ///house
        ///houses
        ///course
        ///case
        ///system
        ///place
        ///end
        ///group
        ///company
        ///companies
        ///party
        ///parties
        ///information
        ///informations
        ///school
        ///fact
        ///money
        ///moneys
        ///point
        ///example
        ///state
        ///business
        ///businesses
        ///night
        ///area
        ///areas
        ///water
        ///thing
        ///family
        ///families
        ///head
        ///hand
        ///order
        ///john
        ///side
        ///home
        ///development
        ///week
        ///power
        ///country
        ///countries
        ///council
        ///use
        ///service
        ///room
        ///market
        ///problem
        ///problems
        ///cou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ThemeSuggestions {
            get {
                return ResourceManager.GetString("ThemeSuggestions", resourceCulture);
            }
        }
    }
}
