//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Puns.WordData", typeof(WordData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Beatles
        ///The Rolling Stones
        ///Bob Dylan
        ///David Bowie
        ///Led Zeppelin
        ///Bruce Springsteen
        ///Prince
        ///The Who
        ///Elvis Presley
        ///Jimi Hendrix
        ///The Beach Boys
        ///R.E.M.
        ///The Velvet Underground
        ///Marvin Gaye
        ///U2
        ///The Clash
        ///Nirvana
        ///Radiohead
        ///Neil Young
        ///Stevie Wonder
        ///Pink Floyd
        ///Elvis Costello
        ///Bob Marley and The Wailers
        ///Van Morrison
        ///Aretha Franklin
        ///Talking Heads
        ///The Smiths
        ///The Byrds
        ///Public Enemy
        ///The Doors
        ///Miles Davis
        ///James Brown
        ///The Kinks
        ///Beastie Boys
        ///Creedence Clearwater Revival
        ///Otis Redding
        ///Michael  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bands {
            get {
                return ResourceManager.GetString("Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harry Potter and the Philosopher&apos;s Stone
        ///The Hunger Games
        ///Twilight
        ///To Kill a Mockingbird
        ///The Great Gatsby
        ///The Fault in Our Stars
        ///1984
        ///Pride and Prejudice
        ///Divergent
        ///The Hobbit
        ///The Catcher in the Rye
        ///The Diary of a Young Girl
        ///Angels and Demons
        ///Animal Farm
        ///The Girl With the Dragon Tatoo
        ///The Kite Runner
        ///The Fellowship of the Ring
        ///Gone Girl
        ///Lord of the Flies
        ///The Help
        ///The Lion, the Witch and the Wardrobe
        ///Romeo and Juliet
        ///The Lovely Bones
        ///The Alchemist
        ///The Girl on the Train
        ///A Game of Thron [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///be
        ///and
        ///of
        ///a
        ///in
        ///to
        ///have
        ///to
        ///it
        ///I
        ///that
        ///for
        ///you
        ///he
        ///with
        ///on
        ///do
        ///say
        ///this
        ///they
        ///at
        ///but
        ///we
        ///his
        ///from
        ///that
        ///not
        ///n&apos;t
        ///by
        ///she
        ///or
        ///as
        ///what
        ///go
        ///their.
        /// </summary>
        internal static string CommonWords {
            get {
                return ResourceManager.GetString("CommonWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a bag of nerves
        ///a bundle of nerves
        ///a bed of roses
        ///a bird in the hand
        ///a bird in the hand is worth two in the bush
        ///a bit much
        ///a blessing in disguise
        ///a blind alley
        ///a bolt from the blue
        ///a bunch of fives
        ///a burnt child dreads the fire
        ///a cat may look at a king
        ///a chain is only as strong as its weakest link
        ///a cinch
        ///a cut above
        ///a damp squib
        ///a dime a dozen
        ///a drop in the ocean
        ///a drowning man will clutch at a straw
        ///a fish out of water
        ///a fool and his money are easily parted
        ///a friend in need is a frie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idioms {
            get {
                return ResourceManager.GetString("Idioms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shawshank Redemption
        ///The Godfather
        ///Soorarai Pottru
        ///The Dark Knight
        ///The Godfather: Part II
        ///12 Angry Men
        ///The Lord of the Rings: The Return of the King
        ///Pulp Fiction
        ///Schindler&apos;s List
        ///Inception
        ///Fight Club
        ///The Lord of the Rings: The Fellowship of the Ring
        ///Forrest Gump
        ///The Good, the Bad and the Ugly
        ///The Lord of the Rings: The Two Towers
        ///The Matrix
        ///Goodfellas
        ///Star Wars: Episode V - The Empire Strikes Back
        ///One Flew Over the Cuckoo&apos;s Nest
        ///Hamilton
        ///Parasite
        ///Interstellar
        ///City of God
        ///Spirited  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
    }
}
