//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WordData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Puns.WordData", typeof(WordData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pablo Picasso
        ///Giotto Di Bondone
        ///Leonardo Da Vinci
        ///Paul Cézanne
        ///Rembrandt Van Rijn
        ///Diego Velázquez
        ///Wassily Kandinsky
        ///Claude Monet
        ///Caravaggio
        ///Joseph Mallord William Turner
        ///Jan Van Eyck
        ///Albrecht Dürer
        ///Jackson Pollock
        ///Michelangelo Buonarroti
        ///Paul Gauguin
        ///Francisco De Goya
        ///Vincent Van Gogh
        ///Édouard Manet
        ///Mark Rothko
        ///Henri Matisse
        ///Raphael
        ///Jean-Michel Basquiat
        ///Edvard Munch
        ///Titian
        ///Piet Mondrian
        ///Piero Della Francesca
        ///Peter Paul Rubens
        ///Andy Warhol
        ///Joan Miró
        ///Tommaso Masaccio
        ///Marc Chagall
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Beatles
        ///The Rolling Stones
        ///Bob Dylan
        ///David Bowie
        ///Led Zeppelin
        ///Bruce Springsteen
        ///Prince
        ///The Who
        ///Elvis Presley
        ///Jimi Hendrix
        ///The Beach Boys
        ///R.E.M.
        ///The Velvet Underground
        ///Marvin Gaye
        ///U2
        ///The Clash
        ///Nirvana
        ///Radiohead
        ///Neil Young
        ///Stevie Wonder
        ///Pink Floyd
        ///Elvis Costello
        ///Bob Marley and The Wailers
        ///Van Morrison
        ///Aretha Franklin
        ///Talking Heads
        ///The Smiths
        ///The Byrds
        ///Public Enemy
        ///The Doors
        ///Miles Davis
        ///James Brown
        ///The Kinks
        ///Beastie Boys
        ///Creedence Clearwater Revival
        ///Otis Redding
        ///Michael  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bands {
            get {
                return ResourceManager.GetString("Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harry Potter and the Philosopher&apos;s Stone
        ///The Hunger Games
        ///Twilight
        ///To Kill a Mockingbird
        ///The Great Gatsby
        ///The Fault in Our Stars
        ///1984
        ///Pride and Prejudice
        ///Divergent
        ///The Hobbit
        ///The Catcher in the Rye
        ///The Diary of a Young Girl
        ///Angels and Demons
        ///Animal Farm
        ///The Girl With the Dragon Tatoo
        ///The Kite Runner
        ///The Fellowship of the Ring
        ///Gone Girl
        ///Lord of the Flies
        ///The Help
        ///The Lion, the Witch and the Wardrobe
        ///Romeo and Juliet
        ///The Lovely Bones
        ///The Alchemist
        ///The Girl on the Train
        ///A Game of Thron [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand
        ///Amazon
        ///Google
        ///Apple
        ///Microsoft
        ///Samsung Group
        ///ICBC
        ///Facebook
        ///Walmart
        ///Ping An
        ///Huawei
        ///Mercedes-Benz
        ///Verizon
        ///China Construction Bank
        ///AT&amp;T
        ///Toyota
        ///State Grid
        ///Disney
        ///Agricultural Bank Of China
        ///WeChat
        ///Bank of China
        ///Home Depot
        ///China Mobile
        ///Shell
        ///Saudi Aramco
        ///Volkswagen
        ///YouTube
        ///Tencent (QQ)
        ///Starbucks
        ///Wells Fargo
        ///BMW
        ///Deutsche Telekom
        ///Moutai
        ///PetroChina
        ///Coca-Cola
        ///Mitsubishi Group
        ///McDonald&apos;s
        ///Taobao
        ///NTT Group
        ///Bank of America
        ///Nike
        ///Porsche
        ///Sinopec
        ///IBM
        ///CITI
        ///Honda
        ///Marlboro
        ///Deloitte
        ///Chase
        ///Tmall
        ///UPS
        ///American Express
        ///Xfinity [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justin Bieber
        ///Taylor Swift
        ///Rihanna
        ///The Countess
        ///Justin Timberlake
        ///Ellen Degeneres
        ///Britney Spears
        ///Cristiano Ronaldo
        ///Kim Kardashian West
        ///Katy Perry
        ///Shakira
        ///Selena Gomez
        ///Jennifer Lopez
        ///Ariana Grande
        ///Demi Lovato
        ///Jimmy Fallon
        ///Oprah Winfrey
        ///P!Nk
        ///Drizzy
        ///Harry Styles
        ///One Direction
        ///Bill Gates
        ///Lebron James
        ///Lil Wayne
        ///Bruno Mars
        ///Kaka
        ///Adele
        ///Niall Horan
        ///Miley Ray Cyrus
        ///Alicia Keys
        ///Kevin Hart
        ///Cameron
        ///Pitbull
        ///Liam
        ///Louis Tomlinson
        ///Nicki Minaj
        ///Neymar Jr
        ///Marshall Mathers
        ///Emma Watson
        ///Avri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Celebs {
            get {
                return ResourceManager.GetString("Celebs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little Drummer Boy
        ///Do You Hear What I Hear?
        ///Santa Baby
        ///Rudolph the Red-Nosed Reindeer
        ///Silver Bells
        ///Carol of the Bells
        ///Linus and Lucy
        ///The Chipmunk Song
        ///I Saw Mommy Kissing Santa Claus
        ///Little Saint Nick
        ///Wonderful Christmastime
        ///Hallelujah
        ///Do They Know It’s Christmas?
        ///Frosty the Snowman
        ///Where Are You, Christmas?
        ///Christmas Bells Are Ringing
        ///Mary, Did You Know?
        ///The Twelve Days of Christmas
        ///The Christmas Shoes
        ///Christmas Time Is Here
        ///I Heard the Bells on Christmas Day
        ///Hark! the Herald Angels Si [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChristmasSongs {
            get {
                return ResourceManager.GetString("ChristmasSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the
        ///be
        ///and
        ///of
        ///a
        ///in
        ///to
        ///have
        ///to
        ///it
        ///I
        ///that
        ///for
        ///you
        ///he
        ///with
        ///on
        ///do
        ///say
        ///this
        ///they
        ///at
        ///but
        ///we
        ///his
        ///from
        ///that
        ///not
        ///n&apos;t
        ///by
        ///she
        ///or
        ///as
        ///what
        ///go
        ///their.
        /// </summary>
        internal static string CommonWords {
            get {
                return ResourceManager.GetString("CommonWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Albania
        ///Algeria
        ///Andorra
        ///Angola
        ///Antigua and Barbuda
        ///Argentina
        ///Armenia
        ///Australia
        ///Austria
        ///Azerbaijan
        ///Bahamas
        ///Bahrain
        ///Bangladesh
        ///Barbados
        ///Belarus
        ///Belgium
        ///Belize
        ///Benin
        ///Bhutan
        ///Bolivia
        ///Bosnia and Herzegovina
        ///Botswana
        ///Brazil
        ///Brunei
        ///Bulgaria
        ///Burkina Faso
        ///Burundi
        ///Côte d&apos;Ivoire
        ///Cabo Verde
        ///Cambodia
        ///Cameroon
        ///Canada
        ///Central African Republic
        ///Chad
        ///Chile
        ///China
        ///Colombia
        ///Comoros
        ///Congo (Congo-Brazzaville)
        ///Costa Rica
        ///Croatia
        ///Cuba
        ///Cyprus
        ///Czechia (Czech Republic)
        ///Democratic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He Stopped Loving Her Today
        ///Crazy
        ///Your Cheatin&apos; Heart
        ///I Fall to Pieces
        ///El Paso
        ///I&apos;m So Lonesome I Could Cry
        ///Today I Started Loving You Again
        ///Lovesick Blues
        ///He&apos;ll Have to Go
        ///The Dance
        ///Sixteen Tons
        ///San Antonio Rose
        ///Workin&apos; Man Blues
        ///I Walk the Line
        ///Mama Tried
        ///Coal Miner&apos;s Daughter
        ///Old Dogs, Children, and Watermelon Wine
        ///Always on My Mind
        ///Oh, Lonesome Me
        ///Tiger By the Tail
        ///Stand by Your Man
        ///Jambalaya
        ///Ring of Fire
        ///For the Good Times
        ///White Lightning
        ///The Last Thing on My Mind
        ///Tennessee Wal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountrySongs {
            get {
                return ResourceManager.GetString("CountrySongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a bag of nerves
        ///a bundle of nerves
        ///a bed of roses
        ///a bird in the hand
        ///a bird in the hand is worth two in the bush
        ///a bit much
        ///a blessing in disguise
        ///a blind alley
        ///a bolt from the blue
        ///a bunch of fives
        ///a burnt child dreads the fire
        ///a cat may look at a king
        ///a chain is only as strong as its weakest link
        ///a cinch
        ///a cut above
        ///a damp squib
        ///a dime a dozen
        ///a drop in the ocean
        ///a drowning man will clutch at a straw
        ///a fish out of water
        ///a fool and his money are easily parted
        ///a friend in need is a frie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Idioms {
            get {
                return ResourceManager.GetString("Idioms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frankly, my dear, I don’t give a damn.
        ///I&apos;m going to make him an offer he can&apos;t refuse.
        ///I coulda had class. I coulda been a contender.
        ///Toto, I&apos;ve got a feeling we&apos;re not in Kansas anymore.
        ///Here&apos;s looking at you, kid.
        ///Go ahead, make my day.
        ///All right, Mr. DeMille, I&apos;m ready for my closeup.
        ///May the Force be with you.
        ///Fasten your seatbelts. It&apos;s going to be a bumpy night.
        ///You talking to me?
        ///What we&apos;ve got here is failure to communicate.
        ///I love the smell of napalm in the morning.
        ///Love means never hav [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MovieQuotes {
            get {
                return ResourceManager.GetString("MovieQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shawshank Redemption
        ///The Godfather
        ///Soorarai Pottru
        ///The Dark Knight
        ///The Godfather: Part II
        ///12 Angry Men
        ///The Lord of the Rings: The Return of the King
        ///Pulp Fiction
        ///Schindler&apos;s List
        ///Inception
        ///Fight Club
        ///The Lord of the Rings: The Fellowship of the Ring
        ///Forrest Gump
        ///The Good, the Bad and the Ugly
        ///The Lord of the Rings: The Two Towers
        ///The Matrix
        ///Goodfellas
        ///Star Wars: Episode V - The Empire Strikes Back
        ///One Flew Over the Cuckoo&apos;s Nest
        ///Hamilton
        ///Parasite
        ///Interstellar
        ///City of God
        ///Spirited  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ain&apos;t Misbehavin&apos;
        ///Annie
        ///Applause
        ///Avenue Q
        ///The Band&apos;s Visit
        ///Beauty and the Beast
        ///Big River
        ///Billy Elliot the Musical
        ///Blood Brothers
        ///The Book of Mormon
        ///Bye Bye Birdie
        ///Cabaret
        ///La Cage aux Folles
        ///Candide
        ///Carmen Jones
        ///Caroline, or Change
        ///Cats
        ///A Chorus Line
        ///City of Angels
        ///Come from Away
        ///The Comedy of Errors
        ///Company
        ///Contact
        ///Crazy for You
        ///Damn Yankees
        ///Dear Evan Hansen
        ///Drood
        ///Evita
        ///Fiddler on the Roof
        ///Fiorello!
        ///Follies
        ///42nd Street
        ///Fosse
        ///Fun Home
        ///A Funny Thing Happened on the Way to th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Musicals {
            get {
                return ResourceManager.GetString("Musicals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like a Rolling Stone
        ///Satisfaction
        ///Imagine
        ///What&apos;s Going On
        ///Respect
        ///Good Vibrations
        ///Johnny B. Goode
        ///Hey Jude
        ///Smells Like Teen Spirit
        ///What&apos;d I Say
        ///My Generation
        ///A Change Is Gonna Come
        ///Yesterday
        ///Blowin&apos; in the Wind
        ///London Calling
        ///I Want to Hold Your Hand
        ///Purple Haze
        ///Maybellene
        ///Hound Dog
        ///Let It Be
        ///Born to Run
        ///Be My Baby
        ///In My Life
        ///People Get Ready
        ///God Only Knows
        ///A Day in the Life
        ///Layla
        ///(Sittin&apos; On) the Dock of the Bay
        ///Help!
        ///I Walk the Line
        ///Stairway to Heaven
        ///Sympathy for the Devil        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a Celebrity ...
        ///The Mighty Boosh
        ///The Shadow Line
        ///Broad City
        ///Skins
        ///RuPaul
        ///Twenty Four
        ///The L Word
        ///Fresh Meat
        ///Gogglebox
        ///Looking
        ///Buffy the Vampire Slayer
        ///Strictly Come Dancing
        ///Entertainment TV
        ///Gavin and Stacey
        ///Veep
        ///The Shield
        ///TV crime drama
        ///US television
        ///A Very English Scandal
        ///The Inbetweeners
        ///Spiral
        ///Science and nature TV
        ///Factual TV
        ///Lost
        ///Shameless
        ///The Good Place
        ///Borgen
        ///Inside No 9
        ///Flight of the Conchords
        ///Six Feet Under
        ///Succession
        ///Sherlock
        ///Wolf Hall
        ///Orange is the New Black
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TVShows {
            get {
                return ResourceManager.GetString("TVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altar
        ///Best Man
        ///Black Tie
        ///Buttonholes
        ///Bow Tie
        ///Bouquet
        ///Bridesmaids
        ///Bride
        ///Bachelor
        ///Budget
        ///Buffet
        ///Bustle
        ///Buttercream
        ///Calligraphy
        ///Canapes
        ///Candle
        ///Caterer
        ///Cathedral
        ///Celebrant
        ///Centrepiece 
        ///Chapel
        ///Charger Plate
        ///Civil Ceremony
        ///Comb
        ///Corsage
        ///Cummerbund
        ///Cutting the Cake
        ///Decorations
        ///Destination Wedding
        ///Dress Code
        ///Drinks Reception
        ///Elopement
        ///Engagement Photos
        ///Entertainment
        ///Evening Reception
        ///Exchanging of Rings
        ///Father of the Bride
        ///Favours
        ///Fiance 
        ///First Look
        ///Florist
        ///Flowers
        ///Flower Gi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wedding {
            get {
                return ResourceManager.GetString("Wedding", resourceCulture);
            }
        }
    }
}
